### ISSUE TITLE
browser.name returns device type, not browser name for iOS

### ISSUE THREAD

**Issue by micahlisonbee** [fnando/browser#121]
When testing with iOS devices (iPad/iPhone) <code>browser.name</code> returns the device type, e.g. ('iPad', or 'iPhone') when it should return 'Safari'. The strange thing is that <code>browser.safari?</code> still returns true.

**Comment by joshdance** [comment]
The ability to get both browser and device on iOS would be great.

**Comment by micahlisonbee** [comment]
@joshdance Hey man.

**Comment by joshdance** [comment]
@micahlisonbee hey!

**Comment by fnando** [comment]
This is now being handled by #204, which isolates platform information in its own object.

**Comment by fnando** [comment]
Fixed by v2.0.0, just released.
