### ISSUE TITLE
Trouble detecting old android browsers

### ISSUE THREAD

**Issue by bdarfler** [fnando/browser#125]
I would like to be able to detect if I'm dealing with the stock Android browser from Android 2.x. However, I am running into two issues.

**Android Platform vs Android Browser**

If I simply use the `android?` method I will end up with a lot of false positives. As seen in [this spec](https://github.com/fnando/browser/blob/master/test/browser_spec.rb) the `android?` method returns true even if the user is using mobile chrome or mobile firefox. This makes sense if `android?` its meant to detect the Android platform but it doesn't get me closer to knowing if the browser in question is the stock Android browser.

**Android Browser Version**

Additionally there is an issue with the `version` method. Take the following UA from a Samsung Galaxy S on Browserstack:
```
Mozilla/5.0 (Linux; U; Android 2.2; en-us; sdk Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
```
The Android OS version is 2.2 which means that I would like trigger my logic for this browser. However, the `version` method returns 4 from the `Version/4.0` section of the UA and not 2.2 from the `Android 2.2` version section of the UA.

**Workaround**

I believe this should work in the interim:
```ruby
browser.ua =~ /Android 4/ && !browser.firefox? && !browser.chrome? && !browser.opera?
```

**Comment by joaocunha** [comment]
:+1:

**Comment by thehappycoder** [comment]
+1
