### ISSUE TITLE
Firefox for android wrong browser name

### ISSUE THREAD

**Issue by tapalilov** [fnando/browser#138]
When browser is  firefox for android,  browser.name method return 'android' as name.

from s5:
```
RuntimeError (#<Browser:0x000000068913d0 @user_agent="Mozilla/5.0 (Android; Mobile; rv:35.0) Gecko/35.0 Firefox/35.0", @accept_language="en-us,bg-bg;q=0.7,en;q=0.3">):
```

from lenovo tablet:
```
RuntimeError (#<Browser:0x007f5b65740e88 @user_agent="Mozilla/5.0 (Android; Tablet; rv:34.0) Gecko/34.0 Firefox/34.0", @accept_language="en-US,en;q=0.5">):
```

**Comment by miketaylr** [comment]
It also fails to detect Firefox OS tablets and browsers. 

@fnando, I'm happy to send a PR with tests if you're interested. Thoughts?

**Comment by fnando** [comment]
Sorry, people. Didn't read these comments, so I implemented it myself.

**Comment by miketaylr** [comment]
cool. :+1:
