### ISSUE TITLE
Better 64-bit Windows vs. 32-bit Windows detection

### ISSUE THREAD

**Issue by coezbek** [fnando/browser#149]
## Description

Please improve 64-bit over 32-bit detection under Windows.
## How to reproduce

Run Chrome 64-bit under Windows 64-bit and visit http://user-agent.herokuapp.com/ 

Observe that x64 is not set to true.
## What do you expect

Common browsers should be detected if running 32-bit or 64-bit.

I like this: http://stackoverflow.com/a/13709431/278842

return browser.ua =~ /x86_64|x86-64|Win64|x64;|amd64|AMD64|WOW64|x64_64/
## Gem version:

Browser version: 0.8.0
## Report

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by coezbek** [comment]
Was anything improved in this regard?

**Comment by fnando** [comment]
There are these methods:

- `browser.platform.windows_x64?`
- `browser.platform.windows_wow64?`
- `browser.platform.windows_x64_inclusive?`
- `browser.platform.windows_rt?`

There isn't much more we can detect, unfortunately.
