### ISSUE TITLE
Platform (OS) version detection

### ISSUE THREAD

**Issue by sergey-alekseev** [fnando/browser#151]
Currently the gem allows to detect [a platform](https://github.com/fnando/browser/blob/6d5bbd05f84583c7c14ee587435aca325d9a0bc7/lib/browser/methods/platform.rb#L131-L140), but doesn't allow to detect a platform's version.  

Platform versions are useful too. E.g. when you have some software that supports only particular operating systems.  

Do you plan to implement such a functionality?

**Comment by fnando** [comment]
This gem became so much more than I firstly imagined it. I think this is beyond the scope of the gem, but It's useful nonetheless. I'm planning to change some things; one idea is making `platform` an object, that responds to `name` and `version` methods.

For now, my suggestion would be monkey-patching this gem, adding the method `platform_version` as you need. Then you can easily upgrade the code once/if we go ahead with these changes.

Makes sense?

**Comment by sergey-alekseev** [comment]
@fnando makes sense. I'll probably take my time doing that later.

**Comment by LawnOni** [comment]
@fnando  That would be a nice one.

Seems to be a great combo with pull request #122, any thoughts?

**Comment by fnando** [comment]
This is now being handled by #204, which isolates platform/device/bot info into separated objects.

**Comment by fnando** [comment]
Fixed by v2.0.0, just released.
