### ISSUE TITLE
[FEATURE] expose ua.yml through Browser 

### ISSUE THREAD

**Issue by cmar** [fnando/browser#162]
We are writing some capybara tests and would love to have access to the user agent strings in ua.yml. We can find it in the Gem, but I was thinking about having something like:

```ruby
  Browser.user_agents['IOS8']
```

I would be happy to create a pull request if it is something your interested in.

In the meantime, @metaskills created this helper method for us:

```ruby
def browser_user_agents
  @browser_user_agents ||= begin
    browser_path = Gem::Specification.find_all_by_name('browser').first.full_gem_path
    ua_yaml_path = File.join browser_path, 'test', 'ua.yml'
    YAML.load(File.read(ua_yaml_path))
  end
end
```

**Comment by fnando** [comment]
Fixed by v2.0.0, just released.
