### ISSUE TITLE
With Windows 10 launching, any chance we could get an official release which includes edge detection

### ISSUE THREAD

**Issue by chrispatterson** [fnando/browser#166]
Apologies for the verbose title.

Looks like the commit last month which added this was https://github.com/fnando/browser/commit/7a82dadeb16baedd9acd7350ce6ae0303b91117f - but the most recent gem release is 0.8 from back in November, and obviously doesn't include this commit.

**Comment by fnando** [comment]
Released v0.9.0. Thanks for pointing this out. ;)
