### ISSUE TITLE
Browser gem not working in Sinatra

### ISSUE THREAD

**Issue by AbdullahMuhammad** [fnando/browser#169]
Gem is not detecting chrome browser not it is detecting my platform i.e linux.

browser = Browser.new(:accept_language => "en-us")
browser.platform => returning empty string
browser.name => always returns other

any help would be appreciated.

**Comment by fnando** [comment]
You're not passing the user agent. Try something like this:

```ruby
browser = Browser.new(ua: request.user_agent, accept_language: request.accept_language)
```

**Comment by AbdullahMuhammad** [comment]
Thank you for your prompt response. 
Yes it works like a charm.
Kindly change the documentation on the read me page.

browser = Browser.new(:ua => "some string", :accept_language => "en-us")
Kindly change it to 
browser = Browser.new(ua: request.user_agent, accept_language: request.accept_language)
