### ISSUE TITLE
Detect Computer

### ISSUE THREAD

**Issue by AbdullahMuhammad** [fnando/browser#170]
Hi, 

Your gem is just awesome. I just want to know how can i detect if the request was initiated from a computer.
At the moment i can see methods that detect it its a mobile, tablet, console, tv etc etc but i cant find computer there. 
Can you please help with this.

**Comment by voke** [comment]
If it's none of the others, I guess you can assume it's a computer?

**Comment by fnando** [comment]
So, detecting things like `computer?` or `web?` or `app?` is really hard because there are too many things to consider (all platforms, all devices, etc). 

I don't think we can do this, but I'm open to suggestions.
