### ISSUE TITLE
Include bot description

### ISSUE THREAD

**Issue by andyinabox** [fnando/browser#172]
The `bots.yml` includes user agent search strings as keys and descriptive strings as values. However, I don't see a method to match the descriptive string.

An example, if I want to explicitly match the Facebook crawler, the following entries in `bots.yml` apply:

```yml
facebookexternalhit: "Facebook Bot"
Facebot: "Facebook Bot" 
```
However, while I can get the key using `browser.bot_name` (in this case, will return either "facebookexternalhit" or "Facebot") there's no method to get the description. So if I want to sniff out the Facebook crawler I still have to use something like this:

```ruby
/(facebook|facebot)/i.match(browser.bot_name)
```

Would be nice if I could do:

```ruby
browser.bot_description.include?("Facebook")
```

**Comment by fnando** [comment]
This is available in v2 as `browser.bot.name`.
