### ISSUE TITLE
Duplicated key in languages.yml

### ISSUE THREAD

**Issue by nekath** [fnando/browser#176]
There are 2 same keys with different value.
```yml
"gd": "Gaelic"
"gd": "Scots Gaelic"
```

This gives a ruby 2.2.3 warning.
```
~/.rvm/gems/ruby-2.2.3/gems/browser-0.4.1/lib/browser/methods/language.rb:42: warning: duplicated key at line 80 ignored: "gd"
```

PR: https://github.com/fnando/browser/pull/175 (remove "gd": "Gaelic")

**Comment by nekath** [comment]
Merged in https://github.com/fnando/browser/pull/175
Closing.

**Comment by maxjacobson** [comment]
I'm seeing this warning still. I think the pull was merged, but a version hasn't been released which includes the change. If there are any blockers preventing release, I'd love to help clear them.
