### ISSUE TITLE
Distinguishing mobile app vs mobile web

### ISSUE THREAD

**Issue by hgani** [fnando/browser#179]
Hi,

Is there a way to distinguish between a request made from a mobile browser (e.g. Safari in iOS) and one made from a webview within an app?

Thanks

**Comment by fnando** [comment]
I just tried iOS simulator and the iOS webview doesn't include the `Safari/:version` part. I'm relying on this to make the detection. Can you try the [ios-webview branch](https://github.com/fnando/browser/tree/ios-webview)?

**Comment by dgilperez** [comment]
+1 (thanks for a great gem, and sorry I cannot try it myself)

**Comment by dgilperez** [comment]
Also, what about Android webview? It looks this is well documented: https://developer.chrome.com/multidevice/user-agent#webview_user_agent

**Comment by samsonasu** [comment]
+1, but I don't think that `browser.safari?` should return true for the webviews.  Our use case involves OTA enterprise app distribution which doesn't work in the webviews and requires standalone safari, which the UIWebKit is decidedly not.  

I can understand how this could cause problems for existing apps, but I believe the correct implementation is not to consider a UIWebView as safari, especially considering the UA for the webviews doesn't include the string "Safari."

**Comment by fnando** [comment]
@samsonasu agree. I changed the detection of webviews and web apps; they aren't detected as Safari anymore. This will require a major versioning bump and warning message, but that's how I think it should be.
