### ISSUE TITLE
Misleading example for ie(6)? in README

### ISSUE THREAD

**Issue by BookOfGreg** [fnando/browser#181]
## Description

[Line 34](https://github.com/fnando/browser/blame/master/README.md#L34) of the current README has an invalid method for checking ie6. `ie(6)?`

## What do you expect

[This branch](https://github.com/BookOfGreg/browser/tree/correcting-readme-for-ie) corrects the readme to `ie?(6)`

## Gem version:

Browser version: Master

**Comment by Feuda** [comment]
Both browser.ie(6)? and  browser.ie(6)? are not woking on Gem version 1.0.1

**Comment by BookOfGreg** [comment]
I agree, this is a fix onto the current master.

**Comment by fnando** [comment]
Merged. Thanks!
