### ISSUE TITLE
Mobiles default browser issue

### ISSUE THREAD

**Issue by git-neelesh** [fnando/browser#189]
Hi Team,

Its working fine for desktop browsers but its not working properly in mobiles browsers, Specially for mobile's default browsers. Please have a look. 

Thanks

**Comment by fnando** [comment]
Can you give more details? Which browser? Which user agent? Running as an app?

Please follow this guide for opening issues: https://github.com/fnando/browser/blob/master/CONTRIBUTING.md#issues

**Comment by git-neelesh** [comment]
In Android default browsers its giving true for *[ browser.chrome? ]* instead false.  its could be return something like Samsung default browser when browser.name so it may help. 

I know default browser headers like Mozila\1.5 ....Chrome\28.0.0 safari\*.*  But my intention is to check weather this is chrome or not. And in case of default browser its getting failed. its happens with all types of mobile's default browser(Android).

By the way thank you so much for your help.
