### ISSUE TITLE
Problem with GoogleBot

### ISSUE THREAD

**Issue by pamit** [fnando/browser#194]
We had a problem with Google webmaster tools (Fetch as Google)
So we ended up with this: "curl -I http://www.wikiooz.ir"

HTTP/1.1 400 Bad Request
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Status: 400 Bad Request
Cache-Control: no-cache
X-XSS-Protection: 1; mode=block
X-Request-Id: e0eb9a68-acd6-43ea-9dff-49e4b6e82e2e
X-Runtime: 0.002393
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Date: Tue, 10 Nov 2015 10:00:40 GMT
Set-Cookie: request_method=HEAD; path=/
X-Powered-By: Phusion Passenger 5.0.10
Server: nginx/1.8.0 + Phusion Passenger 5.0.10

We disabled the before_filter action and everythings went well!

**Comment by fnando** [comment]
What was the error displayed on your application?
