### ISSUE TITLE
undefined method .app?

### ISSUE THREAD

**Issue by niyando** [fnando/browser#208]
## Description

I am trying to use this gem in my rails app. I want to distinguish between request made from app (web view) vs mobile web. As per readme, I am trying `browser.app?` but it raises nomethod exception.

## How to reproduce

Just try to use the method.

## What do you expect

true/false

## What happened instead

`NoMethodError - undefined method `app?' for #<Browser:0x007fee57911a98>`

## Gem version:

Browser version: 1.1.0

Hope this helps.
Thanks,

**Comment by fnando** [comment]
For iOS you can use `browser.platform.ios_app?` and `browser.platform.ios_webview?` (v2.0.0+, just released). There no way of detecting ALL apps, like Android.
