### ISSUE TITLE
Detecting Opera on Android tablet.

### ISSUE THREAD

**Issue by mborecki** [fnando/browser#209]
Condition for detecting Android is:

```
def android?(version = nil)
  !!(ua =~ /Android/ && !opera?) && detect_version?(android_version, version)
end
```

Why there is `!opera` part?

At this moment when I use Opera browser o Android (4.4.2) tablet (acer a1) result I get is:
```
browser.know? -> true
browser.mobile? -> false
browser.tablet? -> false
browser.android? -> false
browser.ios? -> false
browser.opera? -> true
browser.modern -> true
```

My UserAgent is: 
`Mozill/5.0 (Linux; Android 4.4.2; A1-810 Build/KOT49H) Apple/WebKit/537.36 (KHTML, like Gecko) Chrome/48.0.25 64.99 Safari/537.36 OPR/35.0.2070.100283`

**Comment by fnando** [comment]
Fixed by v2.0.0, just released.
