### ISSUE TITLE
`browser.device.mobile?` isn't working

### ISSUE THREAD

**Issue by lucascaton** [fnando/browser#211]
## Description

After updating to version `2.0.0`, neither `browser.mobile?` (expected not to work in this version) nor `browser.device.mobile?` methods work.

## What do you expect

A boolean.

## What happened instead

```
TypeError: no implicit conversion of Hash into String
from lib/browser/device.rb:164:in `match'
```

## Gem version:

Browser version: `2.0.0`

## Report

* Ruby `2.3.0`
* Rails `4.2.5.1`

**Comment by fnando** [comment]
The class constructor now has a different signature. Change the instantiation from `Browser.new(options)` to `Browser.new(ua, options)`, where:

- `ua`: must be a string representing the user agent.
- `options`: must be a hash (for now it only accepts the `accept_language` option).

**Comment by juno** [comment]
Same here.
I investigated the root cause.

In following lines, a `Hash` object passed to `Regexp#match` method and it raises the `TypeError`:
```ruby
    def detect_mobile?
      psp? ||
        /zunewp7/i.match(ua) ||
        /(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i.match(ua) ||
```
(https://github.com/fnando/browser/blob/v2.0.0/lib/browser/device.rb#L164-L165)

This is a workaround:
```diff
diff --git a/lib/browser/device.rb b/lib/browser/device.rb
index 53df9cf..03bebdf 100644
--- a/lib/browser/device.rb
+++ b/lib/browser/device.rb
@@ -4,7 +4,7 @@ module Browser
     attr_reader :ua

     def initialize(ua)
-      @ua = ua
+      @ua = ua[:ua]
     end

     def subject
```

Also, this fixes some query methods like a `silk?`, `xbox?`.

**Comment by fnando** [comment]
@juno please read the message above. The constructor signature has changed. You now have to instantiate it like `Browser.new('some string that represents the user agent', accept_language: 'something')`.

**Comment by juno** [comment]
@fnando 
Yes, I know that.

Since I use Rails integration, I don't instantiate `Browser` object by my hand.
Is Rails integration ready for v2.0.0?
```ruby
    def browser
      @browser ||= Browser.new(
        accept_language: request.headers["Accept-Language"],
        ua: request.headers["User-Agent"]
      )
    end
```
(https://github.com/fnando/browser/blob/v2.0.0/lib/browser/action_controller.rb#L14-L19)

**Comment by fnando** [comment]
@juno you're 100% right. Just pushed a fix for this. I also released v2.0.1.

**Comment by lucascaton** [comment]
Thanks.

**Comment by juno** [comment]
@fnando Wow, Thank you for quick fix!
