### ISSUE TITLE
browser.device.ios? method does not exist

### ISSUE THREAD

**Issue by srecnig** [fnando/browser#219]
In your readme, there's a `browser.device.ios?` method, but it seems like it is not implemented. Now i'm just using ``browser.platform.ios?`` in my app – but the question remains: Should there be such a method? Or is it just a documentation error?

## How to reproduce

add the following test to ios_test.rb: 

```
test "detects ios device" do
  browser = Browser.new(Browser["IOS9"])
  assert browser.device.ios?
end

$ bin/rake TEST=test/unit/ios_test.rb TESTOPTS="--name=test_detects_ios_device"

E

   1) detects ios device
      NoMethodError: undefined method `ios?' for #<Browser::Device:0x007f9993ae3a10>
      # test/unit/ios_test.rb:109

```
## What do you expect
`true` or `false`

## What happened instead

``NoMethodError: undefined method `ios?' for #<Browser::Device:0x007f9993ae3a10>``

## Software:

- Browser gem version: 2.0.2

**Comment by fnando** [comment]
Yeah, the README is wrong. Thanks for catching that. You should use `browser.platform.ios?`.
