### ISSUE TITLE
Crash on #browser_version

### ISSUE THREAD

**Issue by brauliobo** [fnando/browser#222]
`wrong number of arguments (2 for 1)` on line 18 of `lib/browser/generic.rb`
```ruby
    def full_version
      ua[%r[(?:QuickTime)/([\d.]+)], 1] ||
        ua[%r[CoreMedia v([\d.]+)], 1] ||
        "0.0"
    end
```

**Comment by fnando** [comment]
Can you please fulfill the ticket information with all required info? 

https://raw.githubusercontent.com/fnando/browser/master/.github/ISSUE_TEMPLATE.md

**Comment by brauliobo** [comment]
sorry, the problem was that it was recreating the `browser` instance like this: `@browser ||= Browser.new(ua: request.user_agent) `

**Comment by bbuchalter** [comment]
For others affected by this error, my issue was an obsolete and unspecified dependency browsernizer had on this gem for version 1. See https://github.com/assembler/browsernizer/pull/18
