### ISSUE TITLE
Error in Rails 5.beta3

### ISSUE THREAD

**Issue by adrianoresende** [fnando/browser#224]
I updated my project Rails 3.2 to Rails 5.0.0.beta3, and Browser is updated to 2.0.2 too and found bug:

```
Could not render layout: undefined method `mobile?' for #<Browser::Chrome:0x007fec43768428>
```

Is solved when I change version to 1.1.0

**Comment by adrianoresende** [comment]
Rails 4.2.6 has this problem too.

**Comment by fnando** [comment]
Hi, v2 has a new API. As per README, you have to use `browser.device.mobile?` now.
