### ISSUE TITLE
Not working on first request.

### ISSUE THREAD

**Issue by sbatbayar** [fnando/browser#225]
Not working on first request. I'm blocking safari browser to use iframe that showing my web. But it fails on first time. when i go to other page it works.
Rails 3.2.13
Browser 1.1.0
Ruby 1.9.3

**Comment by fnando** [comment]
Can you provide more information like what's the user agent being used and the full backtrace of the exception? Thanks.

**Comment by fnando** [comment]
No feedback, closing this.
