### ISSUE TITLE
[ENHANCEMENT] Extract Regular Expression to Constants

### ISSUE THREAD

**Issue by aselder** [fnando/browser#226]
## Description

Almost all the regular expressions that parse the user_agent string are inline with the methods calls. This results in a new regular expression object being created and the pattern compiled on every call. Since these regular expressions don't change, we can extract them to constants and increase performance and be nice to our friendly GC.

I'll be happy to go through and do this if you think it would be useful.

**Comment by aselder** [comment]
See PR #227.

**Comment by fnando** [comment]
Hey, thanks for your PR.

Just tried something and looks like you don't have to cache regular expressions; only `Regexp.new` will generate new objects, as you can see below. And strings are covered by `frozen_string_literal` magic comment in ruby-2.3+.

```ruby
require "objspace"

GC.disable

def count
  before = ObjectSpace.count_objects[:T_REGEXP]
  1000.times { yield }
  after = ObjectSpace.count_objects[:T_REGEXP]

  [before, after]
end

before, after = count { Regexp.new("foo") }
puts "Regexp.new: from #{before} to #{after}"

GC.start

before, after = count { /foo/ }
puts "/foo/: from #{before} to #{after}"
```
