### ISSUE TITLE
Accept-Language negotiation

### ISSUE THREAD

**Issue by alethea** [fnando/browser#228]
Would it be in scope to add support for Accept-Language negotiation? E.g.: Given a list of locales from `I18n.available_locales`, it would pick the best match?

```ruby
I18n.available_locales
#=> [:en, :es]

browser = Browser.new("Test", accept_language: "fr,en;q=0.5")
browser.negotiate_language(I18n.available_locales)
#=> :en
```

If you think this is in scope, I'm happy to put together a PR.

**Comment by fnando** [comment]
This is a simple (useful) addition but I don't think it's on the gem's scope. You'll be better off by creating a new gem, which can work without browser. Then you can extend browser conditionally with something like this:

```ruby
begin
  require "browser"
  Browser.include YourGem::BrowserExt
rescue LoadError
  # noop
end
```

where `YourGem::BrowserExt` is a module that adds the `negotiate_language(available_locales)` method to `Browser`.

**Comment by alethea** [comment]
Okay, thanks for the feedback. After thinking about this a bit more, I think the behavior is subtle enough that I'd want to leave the implementation up to app delevopers.
