### ISSUE TITLE
why there is no android device?

### ISSUE THREAD

**Issue by natsumesou** [fnando/browser#231]
hello.
We can parse android device name from user agent, but this gem has no android device interface.
Is this for some reason or not?(and I need to get Android device name.)

thank you.

**Comment by fnando** [comment]
Can you give an example? Which user agent are you getting and what's the expected output?

**Comment by natsumesou** [comment]
ok
when Nexus 6P

User-Agent like
```
Mozilla/5.0 (Linux; Android 6.0; Nexus 6P Build/MDA83) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.94 Mobile Safari/537.36
```

and browser.device.name returns
```
"Nexus 6P"
```

regex is like
```
/^.*Android.*?;(?:.*?;)?\s?(?<model_number>.*?)\s?Build.*$/
```

**Comment by fnando** [comment]
The regex needs to be more complex, but I think is possible to get the device name.

And what id should we use for an android-like device (e.g. `browser.device.id`)?

**Comment by natsumesou** [comment]
It's difficult...but I think
```
device_name.delete(' ').downcase.to_sym
```

ex) Nexus 6P
```
:nexus6p
```

is good for id.

**Comment by fnando** [comment]
I don't think dynamically generating the id is a good idea, because we can't rely on it (as it can be anything, e.g. "NOOK BNTV250A").

**Comment by fnando** [comment]
FYI, I just pushed some code to #232 that deals with this. Still need to think about the id though.

**Comment by natsumesou** [comment]
hmm...
i would like to get just device name, and i don't know what is id for.

device.id = :android

is enought for me.
but is this correct use of id?

**Comment by fnando** [comment]
One can use the id to apply some specific stylesheet, for instance. 

Using `android` would be misleading, as that identifies the `platform`. Maybe using something like `:known`, as in "we know what it is, but we can't automatically assign an id".

**Comment by natsumesou** [comment]
download this csv file https://support.google.com/googleplay/answer/1727131
and now we can use reliable model name!
Is this idea realistic?

...it's too difficult to get reliable value from dynamicaly detected value.
