### ISSUE TITLE
Edge 25 detected as Edge 13

### ISSUE THREAD

**Issue by alexander37137** [fnando/browser#235]
## Description
Edge 25 detected as Edge 13

## How to reproduce
Just try to detect latest edge

## What do you expect
Edge version correctly identified

## What happened instead
edge 25 detected as edge 13

## Software:

- Rails version: '4.2.3'
- Browser gem version: '2.0.3'

Possibly it is due edge user agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586"

**Comment by PanfilovDenis** [comment]
+1

**Comment by fnando** [comment]
I can't see how to match Edge 25 in this case. Ideas?

**Comment by fnando** [comment]
This is not something we can handle, so closing this.
