### ISSUE TITLE
facebook crawler

### ISSUE THREAD

**Issue by jonesmac** [fnando/browser#237]
## Description

I believe there is an issue with the facebook crawler not getting through the bot whitelist.

## How to reproduce

I currently use the setup a middleware detector for outdated browsers, similar to that in the documentation:
```
Rails.configuration.middleware.use Browser::Middleware do
  redirect_to '/406' unless browser.modern?
end
```

 for When I go to test the facebook share dialog [here](https://developers.facebook.com/tools/debug/sharing) I constantly get redirected implying the bot didn't pass through.  When I change it to the following, facebook is able to get through no problem.
```
Rails.configuration.middleware.use Browser::Middleware do
  next if browser.ua.include? 'facebookexternalhit'
  redirect_to '/406' unless browser.modern?
end
```

## What do you expect

I expected the built in bot.yml file to allow this, but it appears facebook might have changed the user agent? - More info [here](https://developers.facebook.com/docs/sharing/webmasters/crawler)

## What happened instead

[Describe the actual results]

## Software:

- Rails version: 4
- Browser gem version: 2.0.2

## Full backtrace

```
(No backtrace - just a redirect that shouldn't happen)
```

## Report

Unfortunately the new site isn't live yet so I can't post a url

**Comment by fnando** [comment]
Hi.

There's no bot whitelist. The `bots.yml` file is just a way of detecting bots, not allowing then to do anything. The way you solved (`browser.ua.include?("facebookexternalhit")`) is the way to go.

**Comment by jonesmac** [comment]
So how come some bots seems to work and others don't?

**Comment by jonesmac** [comment]
Google, linkedin, twitter, all had no issues

**Comment by fnando** [comment]
Maybe these other bots have an user agent that is being detected as a modern browser. Just a guess and no actual info to back it up.

Since you're not actually interested on Facebook's, you can replace that line with `next if browser.bot?` and allow all detected bots to access the content.

**Comment by fnando** [comment]
No feedback, closing this.
