### ISSUE TITLE
invalid value for Float(): "0." raise by browser.ie?(['<11'])  (in Opera)

### ISSUE THREAD

**Issue by StefanGreffenius** [fnando/browser#241]
## Description

We use this code:

```ruby
  !browser.ie?(['<11']) 
```

and get this:

```ruby
  `invalid value for Float(): "0."`
```

## How to reproduce

HTTP_USER_AGENT
Opera/9.80 (Windows NT 6.0; WOW64) Presto/2.12.388 Version/12.15

## What do you expect

`true/false` value

## What happened instead

```ruby
  `invalid value for Float(): "0."`
```

## Software:

- Rails version: 4.0.13
- Browser gem version: 2.0.2

## Full backtrace

-

## Report

-

**Comment by fnando** [comment]
What's the user agent?

**Comment by StefanGreffenius** [comment]
`Opera/9.80 (Windows NT 6.0; WOW64) Presto/2.12.388 Version/12.15`

**Comment by fnando** [comment]
Can you check the latest version? This error isn't reproducible:

```
$ pry -rbrowser
2.3.1 (main)> browser = Browser.new("Opera/9.80 (Windows NT 6.0; WOW64) Presto/2.12.388 Version/12.15")
=> #<Browser::Opera:0x007f9a890a6358 @ua="Opera/9.80 (Windows NT 6.0; WOW64) Presto/2.12.388 Version/12.15", @accept_language=[]>
2.3.1 (main)> browser.ie?(["<11"])
=> nil
```

**Comment by StefanGreffenius** [comment]
Hey, i forgot to add the accept_language, without its also working for us in 2.0.2.

```ruby
browser = Browser.new("Opera/9.80 (Windows NT 6.0; WOW64) Presto/2.12.388 Version/12.15", accept_language: "de-DE,ru;q=0.9,de;q=0.8,en;q=0.")
ArgumentError: invalid value for Float(): "0."
```

**Comment by fnando** [comment]
The problem is the accept language value; `de-DE,ru;q=0.9,de;q=0.8,en;q=0.`. See the `en;q=0.`?

I don't know which value this should be (0.1?, 0.0? I don't know). I'll try to read more about the specification for this.

**Comment by fnando** [comment]
There you go:

> If the content-coding is one of the content-codings listed in the Accept-Encoding field, then it is acceptable, unless it is accompanied by a qvalue of 0. (As defined in section 3.9, a qvalue of 0 means "not acceptable.")

http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by StefanGreffenius** [comment]
Amazing thx for research and fix.
