### ISSUE TITLE
Rails - some functions look buggy

### ISSUE THREAD

**Issue by catuss-a** [fnando/browser#245]
## Description

browser.device.mobile? leads to  nil

## How to reproduce

1. gem 'browser'
2. bundle install
3. bundle exec rails s
4. added "#{browser.device.mobile?}" in code

=> nil (chrome browser ubuntu)

## What do you expect

true or false

## What happened instead

got nil as returned value

## Software:

- Rails version: 4.2.4
- Browser gem version: 2.1.0

**Comment by fnando** [comment]
`nil` is a falsy in Ruby, so this is the correct behavior. If you want to display a boolean value, use `"#{!!browser.device.mobile?}"`.

**Comment by catuss-a** [comment]
I see a ? function => return either true or false. not nil or other values. I thought it was pretty mainstream

**Comment by fnando** [comment]
Not really. Here's `Numeric#nonzero?`, from the stdlib:

```ruby
1.nonzero?
=> 1

0.nonzero?
=> nil
```

**Comment by catuss-a** [comment]
@fnando oh ok never noticed that... well ty for your answers !
