### ISSUE TITLE
browser.device

### ISSUE THREAD

**Issue by sposinff** [fnando/browser#246]
## Description

We have our own Device model which appears to be conflicting with your Device model, and therefore browser.device is not working.

## How to reproduce

[Add steps on how to reproduce this issue]

## What do you expect

[Describe what do you expect to happen]

## What happened instead

[Describe the actual results]

## Software:

- Rails version: 4.2.6
- Browser gem version: 2.1.0 (pinned back to 0.8.0)

## Full backtrace

[19] pry(#<WelcomeController>)> b.device
NoMethodError: undefined method `device' for #<Browser:0x007fb7917a5558>
from (pry):16:in `index'

## Report

[Visit <http://user-agent.herokuapp.com> and paste the URL here]

**Comment by fnando** [comment]
That doesn't seem to be the case:

```ruby
class Device; end
=> nil

require 'browser'
=> true

b = Browser.new('')
=> #<Browser::Generic:0x007fd28481a458 @ua="", @accept_language=[]>

b.device.mobile?
=> nil
```

If you're using Rails, did you restart your development webserver after installing the new version?

**Comment by sposinff** [comment]
Yes, multiple times.

```
pry(#<WelcomeController>)> browser`
=> #<Browser:0x007fc3aa2c8510 @accept_language="en-US,en;q=0.8", @user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/50.0.2661.102 Safari/537.36">

pry(#<WelcomeController>)> browser.safari?
=> false

pry(#<WelcomeController>)> browser.chrome?
=> true

pry(#<WelcomeController>)> browser.device?
NoMethodError: undefined method `device?' for #<Browser:0x007fc3aa2c8510>
from (pry):4:in `index'

pry(#<WelcomeController>)> browser.device
NoMethodError: undefined method `device' for #<Browser:0x007fc3aa2c8510>
from (pry):5:in `index'

pry(#<WelcomeController>)> browser.device.name
NoMethodError: undefined method `device' for #<Browser:0x007fc3aa2c8510>
from (pry):6:in `index'

[7] pry(#<WelcomeController>)> browser.to_s
=> "chrome modern mac webkit"

[8] pry(#<WelcomeController>)>
```

**Comment by fnando** [comment]
You're still using an older version somehow. I know this because newer versions (2+) return a different class for browser, in your case it would `Browser::Chrome`).

Can you confirm that your Gemfile.lock has the expected version? You can remove any version from `Gemfile` (e.g. `gem "browser"` instead of `gem "browser", "~> 1.0.0"`). You should also upgrade the installed version with `bundle update browser` after changing your Gemfile.

**Comment by sposinff** [comment]
I had done that multiple times to be sure.  Not sure what I did differently this time, but I am good now.  Thank you.

**Comment by pitops** [comment]
Had the same issue. I have browser gem installed on a separate project which used old version which carried over to this project.

`bundle update browser` did the trick.
