### ISSUE TITLE
suggestion for new feature

### ISSUE THREAD

**Issue by zlx** [fnando/browser#252]
## Description

Find a better name to detect mobile?  desktop?
## What do you expect

It's better to detect mobile? desktop? with the Browser::Base subclass, on the upper layer, just return matched class result
## Software:
- Rails version: [Add rails version here]
- Browser gem version: [Add browser gem version here]
## Example

``` ruby
module Browser
  class Some < Base
    def mobile?
      true
    end

    def desktop?
      false
    end

    def match?
      ua.match?(/some/)
    end
  end
end

Browser.new('some ua').mobile? #=> true
Browser.new('some ua').desktop? #=> false
```
## Report

Just a suggestion? hope you like it.

**Comment by fnando** [comment]
On previous versions of this gem, there were too many methods on `Browser` instance; hence the extraction to specific objects like `platform` and `device`.

I think we can maybe have a new file that adds some _aliases_ to methods like `mobile?` to `Browser` class? Then the developer can, optionally, load it with something like `require "browser/alias"`.

Again, I'm not sure I'd like to add more methods to the main class.

**Comment by zlx** [comment]
Yes, I think it's a good idea
