### ISSUE TITLE
browser.platform.version raises error for macs sometimes

### ISSUE THREAD

**Issue by rhlff** [fnando/browser#255]
## Description

When I try to access the `browser.platform.version` for some Macintosh User-Agents, a `NoMethodError` for the `gsub` call is raised, because the version could not be parsed properly and is `nil`.

When I look at the code for [mac](https://github.com/fnando/browser/blob/master/lib/browser/platform/mac.rb), `gsub` is directly called on the evaluated regex: 
```ruby
ua[/Mac OS X\s*([0-9_\.]+)?/, 1].gsub("_", ".")
```
But the regex seems to be `nil` in some cases.

Other platforms, like [windows](https://github.com/fnando/browser/blob/master/lib/browser/platform/windows.rb), return a `"0"` instead of `nil`. (But they also don't need that `gsub` call.)
```ruby
ua[/Windows NT\s*([0-9_\.]+)?/, 1] || "0"
```

## How to reproduce

Unfortunately we didn't logged the User-Agents on our system. Therefore this issue is hard to reproduce at the moment.

## What do you expect

Return `"0"`, like for other platforms.

## What happened instead

`NoMethodError` raised.

## Software:

- Rails version: 4.2.6
- Browser gem version: 2.1.0

## Full backtrace

```text
E, [2016-06-18T16:34:00.865437 #2209] ERROR -- : [3d4de58] Dispatcher error: NoMethodError: undefined method `gsub' for nil:NilClass
/.../ruby/2.1.0/gems/browser-2.1.0/lib/browser/platform/mac.rb:6:in `version'
/...ruby//2.1.0/gems/browser-2.1.0/lib/browser/platform.rb:90:in `version'
```

**Comment by fnando** [comment]
Can you provide the user agent that is raising the failure?
