### ISSUE TITLE
Browser.device.mobile? returns nil instead of false

### ISSUE THREAD

**Issue by gbarillot** [fnando/browser#270]
Maybe a silly question, but isn't Browser.device.mobile? supposed to return a bool in all cases? Is it normal (backward compatibility?) to get either a true or a "nil" instead of a false? 

If you look at browser.device.tablet?, for example, it works as expected : true or false, but not nil

I'm open to fix it if relevant...

**Comment by ThePletch** [comment]
:+1: This also seems to be happening with `browser.chrome?` and `browser.edge?`, among others.

**Comment by fnando** [comment]
`nil` is a falsy value so this is the correct behavior.

Read my comment on #253 for a more detailed answer.
