### ISSUE TITLE
Implement custom bot 

### ISSUE THREAD

**Issue by rivanenko** [fnando/browser#271]
## Description

Allow adding of custom bot detection
## What do you expect

Add config to specify bots.yml path or a method which allows adding of custom bots

**Comment by fnando** [comment]
You can do this today by settings something like `Browser::Bot.bots["some string the user agent must have"] = "Readable name for the bot"`. If you need to completely erase the bot definition, go with `Browser::Bot.bots.delete_if { true }` and then `Browser::Bot.bots.merge!(new_hash_with_bots_definition)`.

But I agree we should have some public API for this.
