### ISSUE TITLE
Bots are not detected

### ISSUE THREAD

**Issue by ultrablox** [fnando/browser#272]
## Description

browser = Browser.new(req.user_agent)
browser.known? == false

for following user_agent:

Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)
Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)

**Comment by fnando** [comment]
A known browser means that the user agent actually matches a valid browser (e.g. Safari, Chrome, Firefox, etc). For bots, you can use `browser.bot?`.
