### ISSUE TITLE
[feature req] Use gem without ActionController integration

### ISSUE THREAD

**Issue by riffraff** [fnando/browser#274]
## Description

I would like to use the gem but only through the explicit interface of `Browser.new(...)` 
without having the `browser` method appear in controller/view, as the method might 

Maybe a separate pair of `require 'browser'` and `require 'browser/rails'` or two separate gems would be possible? 
## How to reproduce

Add gem
## What do you expect

`browser` does not exist in controller/view but `Browser` does
## What happened instead

`browser` exists in controller/view
## Software:
- Rails version: 4.2
- Browser gem version: 2.2.0

**Comment by fnando** [comment]
Looks reasonable. I'll think of something.
