### ISSUE TITLE
Browser gem is not working with Chrome on MacOS Sierra

### ISSUE THREAD

**Issue by tung-tinypulse** [fnando/browser#278]
## Description

I tried with user agent from Chrome 53.0 on MacOS Sierra and the gem doesn't work

## How to reproduce

* Open rails console and initialize with this user agent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"

`b = Browser.new({:user_agent => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"}) `

* Call method .version
`b.version`

## What do you expect

Browser's version is display properly

## What happened instead

Exception ArgumentError: wrong number of arguments (given 2, expected 1)
[https://cl.ly/3o2s3R0P1A03](screen shot)

## Software:

- Rails version: 4.2.7
- Browser gem version: 2.2.0

## Full backtrace

```text
[Paste full backtrace here]
```

## Report

[Visit <http://user-agent.herokuapp.com> and paste the URL here]

**Comment by fnando** [comment]
Works for me. Can you make sure that you're running the latest version? If you're using Rails, remember to restart the web server after adding the gem to your Gemfile.

```
$ pry
2.3.1 (main)> require 'browser'
=> true
2.3.1 (main)> browser = Browser.new("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36")
=> #<Browser::Chrome:0x007fd745aa6350 @ua="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36", @accept_language=[]>
2.3.1 (main)> browser.version
=> "53"
2.3.1 (main)> Browser::VERSION
=> "2.2.0"
```

**Comment by fnando** [comment]
Something I can't spot from your screenshot: how are you initializing Browser?

**Comment by fnando** [comment]
Oh, your first comment has it. Please use `Browser.new(STRING)`, and not `Browser.new(HASH)`.

**Comment by tung-tinypulse** [comment]
Thanks for your feedback. I can make it works.
