### ISSUE TITLE
Email Clients Support

### ISSUE THREAD

**Issue by abhaykumar** [fnando/browser#281]
## Description

The library is quite good. I am thinking to use for an email marketing project. Can it have email client support also? e.g. Gmail, Outlook, Yahoo, Apple Mail
Please find below link for Reference: 
http://kb.mailchimp.com/lists/managing-subscribers/view-and-target-subscriber-email-clients

## Software:

- Rails version: [Rails 5.0.0]
- Browser gem version: [2.3.0]

**Comment by fnando** [comment]
Seems nice, but I'm not sure how to get a list of user agents so we can add tests and proper code. Any ideas?
