### ISSUE TITLE
Adding Crushlytics/Faraday to bots.yml

### ISSUE THREAD

**Issue by mosheka** [fnando/browser#286]
## Description

We are using the crashlytics.com in our apps.
We would like the crashlytics.com to the list of bots to avoid the 302 response in this case.
crashlytics.comis using the following UA: "Faraday v0.9.2"

We want to add the following line to bots.yml
FARADAY: "Faraday v0.9.2"

## How to reproduce

Use Crushlytics in your app and set it to send notification to your app server

## What do you expect

172.31.1.1 - - [15/Dec/2016:15:48:28 +0000] "POST /api/v1/fabric HTTP/1.1" 200 5 "-" "Faraday v0.9.2"

## What happened instead

This the access log line
172.31.1.1 - - [15/Dec/2016:15:48:28 +0000] "POST /api/v1/fabric HTTP/1.1" 302 5 "-" "Faraday v0.9.2"

## Software:

- Rails version: 2.2
- Browser gem version: 2.2.4

**Comment by fnando** [comment]
Faraday is broad term and won't make to the list. Crashlytics needs to be a good bot citizen and implement a proper user agent. In the meantime, you can do something like 8a8bb43 and extend the bots list in runtime.
