### ISSUE TITLE
Mobile os version not working

### ISSUE THREAD

**Issue by mackshkatz** [fnando/browser#289]
## Description

Getting the os version for a mobile client request is not working

## How to reproduce

calling `browser.platform.version`

## What do you expect

The proper mobile os version

## What happened instead

calling `browser.platform.version` is returning 0 for both ios and android clients:
https://github.com/fnando/browser/blob/master/lib/browser/platform/ios.rb#L8 

The regex seems to be out of sync with what headers are sending through now.

## Software:

- Rails version: 4.2.6
- Browser gem version: 2.2.0

## Report

http://user-agent.herokuapp.com/?ua=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_11_4%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F55.0.2883.95+Safari%2F537.36&accept_language=en-US%2Cen%3Bq%3D0.8

**Comment by fnando** [comment]
That's because, with this user agent informed on the report url, we can't extract anything related to the platform.
