### ISSUE TITLE
Optimise memory usage

### ISSUE THREAD

**Issue by stereobooster** [fnando/browser#291]
## Description

Most of the time there is only one browser per session. So we do not need to load all browser, device classes to detect them. 

```
bundle exec derailed bundle:objects | head -n 100
Measuring objects created by gems in groups [:default, "production"]

allocated memory by gem
-----------------------------------
   1937663  browser-2.3.0
```

## What do you expect

Optimise memory usage the same way as [mini_mime](https://github.com/discourse/mini_mime/) done for [mime-types](https://github.com/mime-types/ruby-mime-types/)

**Comment by fnando** [comment]
This is tricky. The "easiest" way of doing this is by loading major browsers, platforms, and devices. The problems lies on everything that requires precedence. For instance, [some browsers must come before others](https://github.com/fnando/browser/blob/77ec99e46c7bbc99235ecae827aa8008c5dccee0/lib/browser/browser.rb#L53-L55). Do you have any practical solution for cases like this?

**Comment by stereobooster** [comment]
I have no ideas so far. Thanks for the project!
