### ISSUE TITLE
Some old android devices not being recognised as mobile devices

### ISSUE THREAD

**Issue by jkhulme** [fnando/browser#295]
## Description

I tried an old Asus nexus running 4.4 and using chrome as my browser and instead of browser.device.mobile? returning true, it returned nil

The user agent was:
Mozilla/5.0 (Linux; Android 4.4.3; Nexus 7 Build/KTU84L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.78 Safari/537.36

## How to reproduce

```ruby
require 'browser'
browser = Browser.new("Mozilla/5.0 (Linux; Android 4.4.3; Nexus 7 Build/KTU84L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.78 Safari/537.36", accept_language: 'en-us')
browser.device.mobile?
```

## What do you expect

```ruby
browser.device.mobile?
=> true
```

## What happened instead

```ruby
browser.device.mobile?
=> nil
```

## Software:

- Rails version: 4.2.5.2
- Browser gem version: 2.3.0

**Comment by fnando** [comment]
Is your Nexus 7 a phone or tablet?

**Comment by jkhulme** [comment]
tablet

**Comment by fnando** [comment]
So the current behavior is correct. Please use `#tablet?` instead.

**Comment by jkhulme** [comment]
Ah thanks!
