### ISSUE TITLE
Facebook browser not known

### ISSUE THREAD

**Issue by andrewduhan** [fnando/browser#296]
## How to reproduce
browser = Browser.new("Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 [FBAN/FBIOS;FBAV/86.0.0.48.52;FBBV/55555555;FBDV/iPhone9,3;FBMD/iPhone;FBSN/iOS;FBSV/10.2.1;FBSS/2;FBCR/AT&T;FBID/phone;FBLC/en_US;FBOP/5;FBRV/0]")
browser.known?
=> false
browser.name.to_s
=> "Generic Browser"

## What do you expect
browser.known?
=> true
browser.name.to_s
=> "Facebook"

## Software:

- Rails version: 5.0.0.1
- Browser gem version: 2.3.0

**Comment by fnando** [comment]
Is this the user agent when Facebook opens up a page on a web view?

**Comment by JustinMcDonald** [comment]
Here is another example; user agent from an external link opened from iOS Facebook app (uses Facebook browser):

> Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60 [FBAN/FBIOS;FBAV/135.0.0.45.90;FBBV/66877072;FBDV/iPhone9,3;FBMD/iPhone;FBSN/iOS;FBSV/10.3.3;FBSS/2;FBCR/AT&T;FBID/phone;FBLC/en_US;FBOP/5;FBRV/0]
