### ISSUE TITLE
add a mobile? method

### ISSUE THREAD

**Issue by neohunter** [fnando/browser#297]
This is a feature request,

What is your opinion about adding a `mobile?` method to know if the user agent represents a visit from a mobile device? 

Would be nice also to have a `tablet?` method

**Comment by neohunter** [comment]
duh, just noticed both method exists, could you confirm if it will work for any mobile device?

**Comment by chrishough** [comment]
I ended up creating a method for this too for the time being...
```ruby
module BrowserHelper
  def desktop_browser?
    !(browser.device.mobile? || browser.device.tablet?)
  end
end

```

**Comment by jkhulme** [comment]
@neohunter I had an issue the other day where an old android device wasn't recognised as a mobile device
https://github.com/fnando/browser/issues/295

Its worked on all the recent android devices I've tried and all the ios devices I've tried

**Comment by fnando** [comment]
Closing this, since this already exists.

**Comment by chrishough** [comment]
@fnando I do not see a `desktop?` method in the docs... Am I missing something?

**Comment by fnando** [comment]
`desktop?` won't be implemented. Way too hard to do it. It's not just a matter of using `!mobile? && !tablet?`. What about CLIs like cURL or httpie? What about video game consoles? This has been discussed before and we couldn't find any solution for these questions.

**Comment by chrishough** [comment]
Stoked to hear this was a conversation, I see your point, however, I would not consider any of those desktops.
