### ISSUE TITLE
Samsung SmartTV browser detection

### ISSUE THREAD

**Issue by scatmanoleg** [fnando/browser#303]
## How to reproduce
browser = Browser.new("Mozilla/5.0 (SMART-TV; Linux; Tizen 2.4.0) AppleWebkit/538.1 (KHTML, like Gecko) SamsungBrowser/1.1 TV Safari/538.1")
[4] pry(main)> browser.known?
=> true
[5] pry(main)> browser.name.to_s
=> "Safari"
[7] pry(main)> browser.platform.name
=> "Generic Linux"

## What do you expect

[5] pry(main)> browser.name.to_s
=> "SamsungBrowser 1.1"

For example in that way detect browser name this site:
https://www.whatismybrowser.com/developers/tools/user-agent-parser/

**Comment by fnando** [comment]
Sorry for not replying until now.

I don't know how to handle branded browsers like this. IMO, this is a Safari browser. Maybe we should introduce a new set of methods to return that kind of information (`browser.brand.name` and `browser.brand.version`, or something along those lines).

Can you elaborate a little about the use case here?
