### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Ttante** [fnando/browser#308]
## Description
The codebase has changed and the docs are not updated. I'm not sure of everything that changed but browser.device appears to be deprecated and now this works: browser.tablet? and browser.device.tablet? does not.

**Comment by fnando** [comment]
Are you using the latest version?

**Comment by Ttante** [comment]
I'm using 2.3.0. I have version 0.8 listed when i run $ gem list as well, rails could possibly be confusing the versions

**Comment by fnando** [comment]
Make sure you have `gem "browser"` on your Gemfile (I'm assuming you're using Bundler to manage your dependencies.
