### ISSUE TITLE
Otter Browser detection

### ISSUE THREAD

**Issue by m4sk1n** [fnando/browser#309]
## Description

'browser' should detect [Otter Browser](http://github.com/otterbrowser/otter-browser)

## What do you expect

It should be able to detect that I use Otter Browser. Example UA from this browser: 

> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Otter/0.9.91

It doesn't detect it as it should. It's the [result.](http://user-agent.herokuapp.com/?ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F602.1+%28KHTML%2C+like+Gecko%29+Otter%2F0.9.91&accept_language=pl%2C*%3Bq%3D0.9)

**Comment by fnando** [comment]
Released by v2.5.0
