### ISSUE TITLE
Suggestion to add `browser.device.type`

### ISSUE THREAD

**Issue by makoto** [fnando/browser#311]
## Description

Hi, Thank you very much for providing such a comprehensive browser detection library.

I am currently looking for an alternative to a java based user detection library called [user-agent-utils](https://github.com/HaraldWalker/user-agent-utils) as the library is now on end of life.

The library provides [DeviceType](https://github.com/HaraldWalker/user-agent-utils/blob/1027f93ed14a616229230a264651f370f7ccdb18/src/main/java/eu/bitwalker/useragentutils/DeviceType.java) which provides categories such as followings.

- Computer
- Mobile
- Tablet
- Console

I was initially considering using [ua-parser](https://github.com/tobie/ua-parser) but that does not provide as handy functionalities as yours.

I was going to create a method called `device_type` like the following, but wondering if it makes sense to be included as part of `browser` library.

```ruby
browser = Browser.new(string, accept_language: "en-us")
device_type = if browser.device.mobile?
  :mobile
elsif browser.device.tablet?
  :tablet
elsif device.device.console?
  :console
elsif browser.bot?
  :bot
elsif [:chrome_os, :linux, :mac, :windows].any?{|computer| computer == browser.platform.id }
  :computer
else
  :other
end
```

Let me know your thought

Makoto

**Comment by fnando** [comment]
The only issue I have here is that this is mixing information (platform, device, bot detection). I think this is useful, but I'm not yet sold on the method name/placement.

Any suggestions?
