### ISSUE TITLE
Odd IE10 User Agent strings detecting as IE9 and IE8

### ISSUE THREAD

**Issue by jhubert** [fnando/browser#314]
This could simply be a case of bad data, but I was bored and did some exploring. I grabbed [a list of all user agent strings by IE version](http://www.useragentstring.com/pages/useragentstring.php?name=Internet+Explorer) and tested them against browser to check the resulting version.

I came across 3 anomalies in the IE 10 user agents:

```
Mozilla/4.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/5.0) expected to be 10, not 9
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/5.0) expected to be 10, not 9
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/4.0; InfoPath.2; SV1; .NET CLR 2.0.50727; WOW64) expected to be 10, not 8
```

These ones are odd because they are the inverse of the compatibility mode check. The MSIE version reports higher than the trident version.

You can check them at [user-agent.herokuapp.com](http://user-agent.herokuapp.com/?ua=Mozilla%2F5.0%20%28compatible%3B%20MSIE%2010.0%3B%20Windows%20NT%206.1%3B%20Trident%2F4.0%3B%20InfoPath.2%3B%20SV1%3B%20.NET%20CLR%202.0.50727%3B%20WOW64%29) to see the results.

My question is what browser you think these 3 should report at? Is it bad data and are they really meant to be IE 8 and 9, or is it an edge case that should be reporting and IE 10?

My impression is that since Trident is the layout engine, if the Trident value is correct then the features and rendering capabilities should match the Trident version.

**Comment by fnando** [comment]
We use the Trident version to decide the IE version features, as per [Microsoft's documentation](https://msdn.microsoft.com/en-us/library/ms537503(v=vs.85).aspx#TriToken), instead of running browser's version. But one can use different methods for getting this version as well: `msie_full_version` and `msie_version`.

```irb
2.4.1 (main)> browser = Browser.new('Mozilla/4.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/5.0)')
=> #<Browser::InternetExplorer:0x007fc1faaf46f0 @ua="Mozilla/4.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/5.0)", @accept_language=[]>
2.4.1 (main)> browser.msie_full_version
=> "10.0"
2.4.1 (main)> browser.full_version
=> "9.0"
```

IMO, the behaviour is correct when applied to those user agents. What do you think?
