### ISSUE TITLE
Android version 8 is returning version = 0

### ISSUE THREAD

**Issue by jwsf** [fnando/browser#318]
## Description

One of my users is using a new Android device with the following user agent:
`Mozilla/5.0 (Linux; Android 8.0.0; Nexus 5X Build/OPR4.170623.009) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Mobile Safari/537.36`

This is retruning `0` when calling `browser.version`

## How to reproduce

In my rails/rspec tests I'm flashing a message when the browser version is too old, and catching the problem like this:
```
    context "when new Android" do
      it "should not flash a warning message" do
        set_user_agent("Mozilla/5.0 (Linux; Android 8.0.0; Nexus 5X Build/OPR4.170623.009) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Mobile Safari/537.36")
        get :index
        flash.alert.should be_blank
      end
    end
```

## What do you expect

It should return `version=61`

## What happened instead

It returned `version=0`

## Software:

- Rails version: 4.2.5.2
- Browser gem version: 2.4.0

## Full backtrace
Sorry, no device to test this with, only the user agent string

## Report
Sorry, no device to test this with, only the user agent string

**Comment by fnando** [comment]
Can you please try the latest version and see what happens? This is the output I get with 2.5.1:

```irb
2.4.2 (main)> require 'browser'
=> true
2.4.2 (main)> browser = Browser.new('Mozilla/5.0 (Linux; Android 8.0.0; Nexus 5X Build/OPR4.170623.009) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Mobile Safari/537.36')
=> #<Browser::Chrome:0x00007fe81a1da1c8
 @accept_language=[],
 @ua="Mozilla/5.0 (Linux; Android 8.0.0; Nexus 5X Build/OPR4.170623.009) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Mobile Safari/537.36">
2.4.2 (main)> browser.version
=> "61"
2.4.2 (main)> 
```

**Comment by jwsf** [comment]
Yes - fixed in the latest version. Apologies - I didn't realize I was still on an old version.
