### ISSUE TITLE
Incomplete user agents not flagged as bot

### ISSUE THREAD

**Issue by lucke84** [fnando/browser#320]
## Description

Incomplete User agents like `Mozilla/4.0 (compatible;)` are not recognized as bots.

## How to reproduce

```
[1] pry(main)> Browser.new('Mozilla/4.0 (compatible;)').bot?
=> false
[2] pry(main)> Browser.new('Mozilla/4.0 (compatible;)').device.id
=> :unknown
[3] pry(main)> Browser.new('Mozilla/4.0 (compatible;)').platform.id
=> :other
```

## What do you expect

```
Browser.new('Mozilla/4.0 (compatible;)').bot? # => true
```

I think there should be a minimum set of browser info to flag a user agent as "human". The combination `device.id == :unknown && platform.id == :other` could be a way to validate that.

## What happened instead

```
Browser.new('Mozilla/4.0 (compatible;)').bot? # => false
```

## Software:

- Rails version: 5.x
- Browser gem version: 2.5.1

## Full backtrace

N/A

## Report

N/A

**Comment by fnando** [comment]
I like the idea of classifying devices and platforms as bots. I'm gonna implement something!
