### ISSUE TITLE
Wrong interpretation of user-agent?

### ISSUE THREAD

**Issue by marcelrouw** [fnando/browser#328]
## How to reproduce

> b = Browser.new("Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G935F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.2 Chrome/56.0.2924.87 Mobile Safari/537.36")
 => #<Browser::Chrome:0x00007fe4a0df3068 @ua="Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G935F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.2 Chrome/56.0.2924.87 Mobile Safari/537.36", @accept_language=[]>
> b.chrome?
 => true
> b.version
 => "56"
> b.platform.android_webview?
 => nil

## What do you expect

Was not expecting `b.chrome?` to be true. Because this is a webview. But this can be new behaviour. (We recently updated from 2.3.0)
If `b.chrome?` returns correctly true I would expect `b.platform.android_webview?` at least to be true. So I can distinguish between normal chrome and webview chrome.

## Software:

- Rails version: 4.2.x
- Browser gem version: 2.5.2

**Comment by fnando** [comment]
There's no easy way of making this happen. According to the existing test case, Android webview adds a `wv` to the user agent, which I can't see it on your user agent. Which app is making the request without the `wv`?
