### ISSUE TITLE
detect_mobile? for firefox 61

### ISSUE THREAD

**Issue by seb-sykio** [fnando/browser#360]
the method detect_mobile? seems to not work for mobile with firefox 61

Mozilla/5.0 (Android 8.1.0; Ta…61.0) Gecko/61.0 Firefox/61.0

**Comment by Nasaakaa** [comment]
@seb-sykio hi, is it working?

**Comment by fnando** [comment]
Is the whole user agent? Looks like is cropped (`Ta…61.0`).
