### ISSUE TITLE
Facebook in-app browser not known

### ISSUE THREAD

**Issue by martijnvdh** [fnando/browser#374]
## Description
Facebook in-app browser on IOS not recognized anymore.

Using the facebook app (version 213.0) gives you the following user-agent:
"Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16D57 [FBAN/FBIOS;FBDV/iPhone11,2;FBMD/iPhone;FBSN/iOS;FBSV/12.1.4;FBSS/3;FBCR/KPN NL;FBID/phone;FBLC/en_GB;FBOP/5]"

Seems like "FBAV" is not included anymore.

## How to reproduce
browser = Browser.new("Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16D57 [FBAN/FBIOS;FBDV/iPhone11,2;FBMD/iPhone;FBSN/iOS;FBSV/12.1.4;FBSS/3;FBCR/KPN NL;FBID/phone;FBLC/en_GB;FBOP/5]")

browser.known?
=> false
browser.name.to_s
=> "Generic Browser"

## What do you expect
browser.known?
=> true
browser.name.to_s
=> "Facebook"

## Software
Rails version: 5.1.2
Browser gem version: 2.5.3

**Comment by Gregdebrick** [comment]
+1 would be very usefull (Facebook & Instagram if possible)
