### ISSUE TITLE
Yandex Search Browser is detected as bot

### ISSUE THREAD

**Issue by GeorgeGorbanev** [fnando/browser#382]
## Description

Yandex Search Browser is detected as bot

## How to reproduce

1. Open [Yandex Search App](https://mobile.yandex.ru/apps/iphone/search/)
2. Access your site
3. Browser gem detect your access as bot

## What do you expect

Yandex Search App Browser is device mobile

## What happened instead

Yandex Search App Browser is bot

## Software:

- Rails version: 4.2
- Browser gem version: 2.5.3

## Report

Fixed here
Commit https://github.com/GeorgeGorbanev/browser/commit/d8d67d54c5cc10ea543ae0770311b1a06ddea4eb
PR  https://github.com/fnando/browser/pull/383

**Comment by fnando** [comment]
Closed via e709be40225c5563acb54419dbdfec4cb7ff1a73 due to conflicts.
