### ISSUE TITLE
Inconsistent behaviour when using Yandex on different devices

### ISSUE THREAD

**Issue by stevebissett** [fnando/browser#397]
## Description

First off, thanks for a great gem, and all the work done on it.

After working with a site with an increasing Russian user base, it has become apparent that the the Yandex browser is used by up to 20% of users ([StatsCounter lists this](http://gs.statcounter.com/browser-market-share/all/russian-federation) as 13.46% of the wider Russian internet user population)

It also became evident that the system using this gem has been misclassifying Yandex Browser uses as Chrome or Safari users. 

It appears that: 
-  iOS Yandex users are classified as Safari users `browser.id == :safari => true`
- Windows / Mac OS X users are classified as Chrome users `browser.id == :chrome => true`

Given the name of this gem, my initial expectation was that I'd be able to retrieve the name of a browser (even if it is using Chrome / Chromium / WebKit under the hood). I find the current behaviour quite unexpected (and others may experience the same issue as a result). 

It is possible to work around this gem in my Rails App by adding conditionals. This is okay, but then results in browser user agent logic outside of the gem (and the app needs to know more about browsers) 

```
browser.yandex? ? :yandex_browser : browser.id
```

In conversation, it would go something like this: "Which browser do you use?", and the response could be something like "I use Yandex on my Mac". Another justification for this thinking is the kind of output we would see on https://www.whatismybrowser.com, for which I get the following (after installing Yandex): 

<img width="817" alt="Screenshot 2019-07-16 at 23 09 06" src="https://user-images.githubusercontent.com/5316630/61329927-bd4df980-a81e-11e9-875a-c05b81adff98.png">

I am aware of some other Yandex issues that have been raised in the past. Feel free to point me to conversations in those that may be relevant: 
https://github.com/fnando/browser/issues/382
https://github.com/fnando/browser/issues/183
https://github.com/fnando/browser/issues/267
https://github.com/fnando/browser/issues/295

## How to reproduce

1. Navigate to the source directory
2. With `irb` installed, run ` irb -I lib -r browser`, or open a ruby console and require the dependency.
3. Create new Browser objects with the following user agent strings (`Browser.new(user_agent_string)`): 

```
YANDEX_BROWSER_DESKTOP: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 YaBrowser/19.6.0.1583 Yowser/2.5 Safari/537.36"
```

```
YANDEX_BROWSER_IOS: "Mozilla/5.0 (iPhone; CPU iPhone OS 12_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 YaBrowser/19.6.1.157.10 Mobile/15E148 Safari/605.1"
```

## What do you expect

In both cases, I expect the following: 

```
browser.id should equal :yandex_browser or :yandex
browser.name should equal :yandex_browser or :yandex
browser.chrome? should equal false
browser.safari? should equal false
browser.yandex? should equal true
```

## What happened instead

Case 1 (Desktop / Mac) 
```
browser.id was equal to :chrome
browser.name was equal to :chrome
browser.chrome? was equal to true
browser.yandex? was equal to true
```

Case 2 (Mobile / iPhone) 

```
browser.id was equal to :safari
browser.name was equal to :safari
browser.safari? was equal to true
browser.yandex? was equal to true
```

I would argue that Browser X is built on WebKit, or Browser Y is based on Chromium, but not that Browser Y is Chrome. 

## Software:

- Rails version: Rails 5.2.3
- Browser gem version: 2.6.1

## Full backtrace

There is no backtrace for this issue, because an exception is not raised. (The behaviour is unexpected) 

## Report

I do not have the report from mobile, because I have not installed this on my mobile device (I have an Android mobile)

http://user-agent.herokuapp.com/?ua=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_14_5%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F74.0.3729.169+YaBrowser%2F19.6.0.1583+Yowser%2F2.5+Safari%2F537.36&accept_language=af%2Cen-US%3Bq%3D0.9%2Cen%3Bq%3D0.8

## Pull Request 

I am going to submit a PR with these ideas, feel free to engage with them, I would like to understand your perspective or any kind of objections or concerns that you might have (backwards compatibility could be one of them).

**Comment by fnando** [comment]
Fixed on #413.
