### ISSUE TITLE
Translation to others language

### ISSUE THREAD

**Issue by truongnmt** [fnando/browser#399]
Is there any way to translate output to language other than English?
For eg: localize Japanese

Generic Linux (Opera) -> 基本Linux（Opera)
Windows (Generic Browser)　→　Windows（基本ブラウザ）

Or devs can add yml translation file and the rest will use English as default.

**Comment by fnando** [comment]
I think this can be achieved as a 3rd party plugin that receives the browser name and returns the expected translation.

In practice, it'd be a matter of having all browser names translated in a i18n file and call `I18n.t(browser.name)`, which would then search for entries like you mentioned.
