### ISSUE TITLE
Does not work within Capybara Tests

### ISSUE THREAD

**Issue by lflucasferreira** [fnando/browser#400]
## Description

Hey there, I was trying to use this gem in order to capture all browser information to save it directly to the database during my testing. I use Capybara and Cucumber, but it does not detect the robot browser.  I added browser.platform.other? and it returned TRUE while it is a Windows machine. 

Well, I believe this gem is not supposed to be used by Testers within their workspaces.

## Software:

browser (2.6.1)
Summary: Do some browser detection with Ruby.
Homepage: http://github.com/fnando/browser
Path: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/browser-2.6.1

**Comment by fnando** [comment]
What does capybara/cucumber use as the user agent?

**Comment by lflucasferreira** [comment]
Well, never mind bro. I found out I missed the UA information when creating a new instance. Thanks.
