### ISSUE TITLE
Amigo Browser detected as bot

### ISSUE THREAD

**Issue by GeorgeGorbanev** [fnando/browser#401]
## Description

Amigo Browser is detected as bot

## How to reproduce

1. Open [Amigo Browser](https://amigo.mail.ru/)
2. Access your site
3. Browser gem detect your access as bot

## What do you expect

Amigo Browser is not detected as bot

## What happened instead

Amigo Browser is detected as bot

## Software:

- Rails version: 4.2
- Browser gem version: 2.5.3

User agent example:
```
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.125 Amigo/61.0.3163.125 MRCHROME SOC Safari/537.36
```

## Report

Bot is detecting because of [this string](https://github.com/fnando/browser/blame/master/bots.yml#L149) that was added in [this commit](https://github.com/ellimist/browser/commit/b3302169ae5d2015372c5c4afa376fad0e4e33f9) for [this issue](https://github.com/fnando/browser/issues/205)

Guess "Looks like undetected bot" is wrong motivation. It is real browser with real users.

**Comment by fnando** [comment]
Fair enough. I'll remove `MRCHROME` from the list.
