### ISSUE TITLE
Chrome Webview Inside an App as Bot

### ISSUE THREAD

**Issue by keviinlouis** [fnando/browser#402]
## Description

When a user agent comes from a chrome webview inside an app, the class Browser reconizes as bot
This occurs when the phone has this app installed https://twrp.me/samsung/samsunggalaxya8plus2018.html

## How to reproduce

Instanciate a class Browser

`browser = Browser.new("Mozilla/5.0 (Linux; Android 9; SM-A730F Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/76.0.3809.89 Mobile Safari/537.36 Instagram 105.0.0.18.119 Android (28/9; 420dpi; 1080x2094; samsung; SM-A730F; jackpot2lte; samsungexynos7885; pt_BR; 166149717)", accept_language: "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7")`

Then run `bot?`

`browser.bot?`

## What do you expect

I expect the result to be `false` 

## What happened instead

the result returns `true`

## Software:

- Rails version: 4.2.10
- Browser gem version: 2.5.3

If you'll  add for Instagram, plz add to Facebook and Twitter
This error occurs mostly with smartphones of models SM-A730F and SM-A530F

**Comment by fnando** [comment]
The reason is that there's a bot called `jack` that's matching `jackpot2lte` incorrectly. I'll try to think of something. 🤔
