### ISSUE TITLE
Snapchat in-app browser is detected as bot

### ISSUE THREAD

**Issue by danielwwong** [fnando/browser#407]
## Description

Here's the UA for snapchat in-app browser:
`Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Snapchat/10.69.5.72 (iPhone10,3; iOS 13.2.2; gzip)`

It is categorized as `bot`. And `browser.name` returns `Generic Browser`, not `Snapchat`.

## How to reproduce

```
> browser = Browser.new 'Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Snapchat/10.69.5.72 (iPhone10,3; iOS 13.2.2; gzip)'
> browser.name
=> "Generic Browser"
> browser.bot?
=> true
> browser.bot.name
=> "Snapchat"
```

## What do you expect

`browser.name` returns `Snapchat`

## What happened instead

`browser.name` returns `Generic Browser`

## Software:

- Browser gem version: 2.6.1

**Comment by SArnett** [comment]
@fnando, I noticed that `browser.bot?` from the example is still returning `true` for the in-app browser on Snapchat. I just wanted to check if this is an intended behavior. Thanks!
