### ISSUE TITLE
Bot detection fails several common bots

### ISSUE THREAD

**Issue by DanielHeath** [fnando/browser#426]
## Description

I'm using browser 2.7.1, and recording UAs & bot status in my production analytics.

I'm seeing quite a few obvious-bots which are not reported as such: 

The following UAs do not detect as known browsers / bots:
```
Buck/2.2; (+https://app.hypefactors.com/media-monitoring/about.html)
Jaunt/1.5
Mozilla/5.0 (compatible; coccocbot-web/1.0; +http://help.coccoc.com/searchengine)
Mozilla/5.0 (compatible) SemanticScholarBot (+https://www.semanticscholar.org/crawler)
weborama-fetcher (+http://www.weborama.com)
```

**Comment by fnando** [comment]
There's no automatic bot detection, even when the user agent explicitly have `bot` in it. Maybe we should have something configurable to reject everything that has such string on the user agent?

```ruby
Browser::Bot.matchers << -> (ua) { ua =~ /bot|crawler|fetcher/i }
```

It wouldn't match the first one automatically though.

**Comment by fnando** [comment]
This is the actual implementation: https://github.com/fnando/browser/pull/427

**Comment by fnando** [comment]
https://github.com/fnando/browser/pull/429 will match all but `Jaunt` automatically, but I added a rule for it.

**Comment by fnando** [comment]
#429 has been merged.
