### ISSUE TITLE
memoize Bot#bot?

### ISSUE THREAD

**Issue by gurgeous** [fnando/browser#437]
Thanks for creating this gem. We love it and use it all over the place. So handy.

Let's memoize this guy!

```ruby
class Bot
  def bot?
    return @bot if defined? @bot
    @bot = !bot_exception? && detect_bot?
  end
end
```

**Comment by fnando** [comment]
Hey @gurgeous!

Although I can definitely see the benefit, I think this is better off as a custom wrapper you keep in your own project, like your example. Browser has a big surface and memoization introduces additional complexity that I'm not convinced is worth bringing to the project.

Maybe there's a gem somewhere that takes all methods defined by a class and memoize them?
