### ISSUE TITLE
[Feature idea] Version of browser similar to gem version constraint

### ISSUE THREAD

**Issue by mobilutz** [fnando/browser#440]
## Description

As an idea, it would be cool to be able to use something like this:
```
browser.firefox?('>= 17')
browser.chrome?('>= 40')

# or

browser.firefox?(17, min: true)
browser.chrome?(40, min: true)
```
to allow a mimimum version requirement.

So using version pattern which is for example used in Gemfiles.

## What do you expect

Expectation would be to not just match to a specific version of a browser, but using the passed version number as a minimum requirement.

**Comment by fnando** [comment]
Hey @mobilutz! The first suggestion you gave already exists. You can check the [methods that support a version requirement here](https://github.com/fnando/browser/blob/657828513b4b8ba9883f69da5f3e0149466354d6/lib/browser/base.rb).

We should probably improve the documentation about this feature. 🤔

**Comment by mobilutz** [comment]
@fnando Ah, now I see it:
https://github.com/fnando/browser/blob/master/lib/browser/detect_version.rb#L19

I didn't look at that method in detail. And also not the tests:
https://github.com/fnando/browser/blob/master/test/browser_test.rb#L74

Yes, documentation for that would be cool. Maybe I can find some time to write things down.

**Comment by mobilutz** [comment]
PR for the Readme: https://github.com/fnando/browser/pull/441
