### ISSUE TITLE
method meta still uses "modern?"

### ISSUE THREAD

**Issue by mikaelprag** [fnando/browser#442]
## Description

While removing the "modern?" method I was surprised to see that I was still getting deprecation messages in the logs while running a test suite even after it was replaced with the new recommended method. The issue seems to be that the "meta" method that the browser.to_s uses, still uses the deprecated "modern?" method.

## How to reproduce

browser = Browser.new('Some User Agent' , accept_language: 'en-us')
browser.to_s

## What do you expect

No deprecation message.

## What happened instead

Deprecation message shows:

Browser::Base#modern? is now deprecated.
Check https://github.com/fnando/browser/issues/435 for details.

## Software:

- Rails version: 2.6.2
- Browser gem version: 3.0.3, master

**Comment by fnando** [comment]
Fixed by v4.0.0. ;)
