### ISSUE TITLE
iPad Pro webviews not detected

### ISSUE THREAD

**Issue by asad-imtiaz** [fnando/browser#446]
I am using browser gem's `browser.platform.ios_webview?` method to detect requests coming from iOS webviews.

It seems to work fine except for the iPad Pro. For iPad Pro this method returns false instead of true.

Any idea why this might be happening?

- Rails version: 5.2
- Browser gem version: 4.0.0

**Comment by fnando** [comment]
Can you please post the user agent?

**Comment by asad-imtiaz** [comment]
User Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) WeTime iOS"

**Comment by saikiransripada** [comment]
@fnando I ran into the same error. Is there any solution to this issue?

**Comment by fnando** [comment]
I believe this is related to https://github.com/fnando/browser/issues/404. There's nothing I can do, unfortunately.

**Comment by asad-imtiaz** [comment]
@saikiransripada I got it to work.
Apparently, the platform on iPad Pro is not iOS, it is Mac OS. And according to the code in the gem, they determine that it is a webview by checking that the user agent should not contain `"safari"`.

So, if the following is true then it's an iPad Pro webview:
`browser.platform.name.downcase.include?('macos') && !request.user_agent.downcase.include?('safari')`

this worked for me.

**Comment by adrienpoly** [comment]
Thanks @asad-imtiaz you made my day

**Comment by QasimQureshi** [comment]
Testing the solution @asad-imtiaz suggests - in 2024 and iPadOS 17.1.1, the platform name iPad Pro 12.9 reports is "macintosh".
