### ISSUE TITLE
Google Image Proxy detection

### ISSUE THREAD

**Issue by scebotari** [fnando/browser#448]
## Description

Gmail uses a service called Google Image Proxy (found a good description [here](https://www.scientiamobile.com/what-is-google-image-proxy/)). The issue is that this service proxies any requests for image resources and changes the original user agent string.

## How to reproduce

Send an email with a random image. When email is opened, image is loaded trough Google Image Proxy (not consistent, happens some times).

Google Image Proxy user agent: `Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)`

## What do you expect

Browser name `Google Image Proxy`, and `proxy?` to be`true`:
```
irb(main):002:0> browser = Browser.new('Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)')
=> #<Browser::Firefox:0x000055fc40c7f208 @ua="Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)", @accept_language=[]>
irb(main):003:0> browser.known?
=> true
irb(main):004:0> browser.name
=> "Google Image Proxy"
irb(main):005:0> browser.bot?
=> false
irb(main):006:0> browser.proxy?
=> true
```

It's not a bot, because it's a real request proxy-ed through google Image Proxy.

## What happened instead

Email was opened in Chrome, but I stated before original UA was replaced and "Firefox" is detected instead:
```
irb(main):002:0> browser = Browser.new('Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)')
=> #<Browser::Firefox:0x000055fc40c7f208 @ua="Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)", @accept_language=[]>
irb(main):003:0> browser.known?
=> true
irb(main):004:0> browser.name
=> "Firefox"
irb(main):005:0> browser.bot?
=> false
irb(main):006:0> browser.proxy?
=> nil
```

## Software:

- Rails version: Rails 5.2.0
- Browser gem version: 4.0.0

**Comment by fnando** [comment]
The `proxy?` method is not meant for bots; instead, it's a way of detecting browser that have built-in proxy system.

I do agree that it should be detected as a bot though.

**Comment by fnando** [comment]
Oh, so you think it should not be detected as a bot. 🤔

The thing is, other image proxies are being detected as bots, so we cannot open an exception for Google Image Proxy, like [Slack's](https://github.com/fnando/browser/blob/cef3380e5ff7ef943f398e91e0d9a9a0393c35b9/bots.yml#L220).

I'm down to add this as a bot, but would like to hear your opinion first.
