### ISSUE TITLE
iOS doesn't detect microsoft edge browser

### ISSUE THREAD

**Issue by luissimo** [fnando/browser#454]
Microsoft Edge browser is not detected for iOS devices (it returns Safari)

The user agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 EdgiOS/44.5.0.10 Mobile/15E148 Safari/604.1"

Returns Safari but it should recognize the 'EdgiOS' part.

**Comment by libuchao** [comment]
```
Mozilla/5.0 (Linux; Android 7.1.2; Redmi 4X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.0 Mobile Safari/537.36 EdgA/44.11.2.4122
```

Edge for Android returns Chrome
