### ISSUE TITLE
Brave browser not detected on all platforms

### ISSUE THREAD

**Issue by luissimo** [fnando/browser#455]
The Brave browser is not detected and returns wrong browser name (eg. Safari for iOS).

Example user agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) brave/0.8.3 Chrome/49.0.2623.108 Brave/0.37.3 Safari/537.36"

Could perhaps be solved by adding new method checking for "ua =~/Brave/"

Brave user agents: (https://developers.whatismybrowser.com/useragents/explore/software_name/brave/)

I was using Brave v1.15 to detect brave so maybe it is not possible at all with that version (https://github.com/brave/brave-ios/issues/2210)

**Comment by fnando** [comment]
I tried for myself and installed Brave on iOS, Android, Mac and Windows. There's no parseable user agent in any of them.

- [Brave v1.16 on iOS](http://user-agent.herokuapp.com/?ua=Mozilla%2F5.0+%28iPhone%3B+CPU+iPhone+OS+13_4_1+like+Mac+OS+X%29+AppleWebKit%2F605.1.15+%28KHTML%2C+like+Gecko%29+Version%2F13.1+Mobile%2F15E148+Safari%2F604.1&al=en-ca)
- [Brave v1.7.102 on Android](https://user-agent.herokuapp.com/?ua=Mozilla%2F5.0+%28Linux%3B+Android+10%3B+Mi+A2%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F81.0.4044.122+Mobile+Safari%2F537.36&al=en-CA%2Cen%3Bq%3D0.9%2Cpt-BR%3Bq%3D0.8%2Cpt%3Bq%3D0.7%2Cen-GB%3Bq%3D0.6%2Cen-US%3Bq%3D0.5)
- [Brave v1.8.95 on Mac](https://user-agent.herokuapp.com/?ua=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_15_4%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F80.0.3987.87+Safari%2F537.36&al=en-US%2Cen%3Bq%3D0.9)
- [Brave v1.8.95 on Windows](https://user-agent.herokuapp.com/?ua=Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/81.0.4044.138+Safari/537.36&al=en-US,en;q%3D0.9)

I don't think it makes sense adding detection for old versions.
