### ISSUE TITLE
iPad detection

### ISSUE THREAD

**Issue by aleksander-tatskiy** [fnando/browser#464]
Hi, could you fix iPad detection?

`browser.device.ipad?` is not working any more

For example, 
Safari: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15

**Comment by fnando** [comment]
iPads cannot be detected anymore. Please check https://github.com/fnando/browser/issues/404 for details. tl;dr: the user agent doesn't bring any information about iPad from iOS 13 onwards.

**Comment by gregblass** [comment]
Blame Apple. So ridiculous.
