### ISSUE TITLE
Only Major version is used to detect Safari browser

### ISSUE THREAD

**Issue by aslam** [fnando/browser#465]
## Description

Detect if the browser is Safari only the [major version is being used](https://github.com/fnando/browser/blob/master/lib/browser/base.rb#L125) instead of `full_version`, like for other browsers, which gives wrong results.

## How to reproduce

```
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15"
browser = Browser.new(user_agent)

browser.version # 11
browser.full_version # 11.1.2

browser.safari?(">= 11.1") # false
```
## What do you expect

`browser.safari?(">= 11.1")` should return true.

## What happened instead

As described above, this returns false.

## Software:

- Rails version: 5.1.7
- Browser gem version: 4.0.0

**Comment by fnando** [comment]
Good catch! I fixed this on https://github.com/fnando/browser/commit/85fd456bd12c7e34dcc749bfada9b4ca5447c834 but it not yet released.
