### ISSUE TITLE
Rails 6: Stack level too deep

### ISSUE THREAD

**Issue by joeltaylor** [fnando/browser#488]
## Description
Calling `browser.meta` followed by `browser.device.to_json` results in a `SystemStackError: stack level too deep`.

It appears that calling `browser.meta` causes `browser.device` to be recursive.

## How to reproduce
Create a new rails app with a basic controller
```
rails new sample

rails generate controller Welcome index
```

Add `browser` to the Gemfile
```
gem 'browser'
```

Add the following code to`Weclome#index`
```
def index
  browser.meta
  browser.device.to_json
end
```
Visit `localhost:3000/welcome/index`

## What do you expect

Expected `browser.device.to_json` to successfully be serialized to JSON.

## What happened instead
An error is raised: 
```
SystemStackError: stack level too deep
from ~/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/core_ext/object/json.rb:172:in `dup'
```

## Software:

- Rails version: `6.0.3.2`
- Browser gem version: `4.2.0` and the `main` branch
- Ruby version: `2.6.6p146`

## Full backtrace

```text
Processing by WelcomeController#index as HTML
Completed 500 Internal Server Error in 27ms (ActiveRecord: 0.0ms | Allocations: 9223)

SystemStackError (stack level too deep):

app/controllers/welcome_controller.rb:4:in `index'

```

## Report
https://user-agent.herokuapp.com/?ua=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10.15%3B+rv%3A79.0%29+Gecko%2F20100101+Firefox%2F79.0&al=en-US%2Cen%3Bq%3D0.5

**Comment by fnando** [comment]
Currently, there's no serialization support because I never needed it, and nobody asked for this feature before.

Right now, your best bet is writing your own serializer. `meta` uses `browser.device` internally, so we may have to do some caching on those classes.

**Comment by joeltaylor** [comment]
@fnando thanks for taking a look! I believe my expectations were a bit off kilter as I was expecting it to serialize simply because it worked in Rails 5 and I wasn't working with the JSON payload. Considering the predicate methods, I think your suggestion for a custom serializer makes sense. If we end up needing a JSON payload, we'll take that route. Thanks!
