### ISSUE TITLE
Samsung devices are not identified

### ISSUE THREAD

**Issue by koendehondt** [fnando/browser#494]
## Description

Samsung devices are not identified.

## How to reproduce

b = Browser.new("Mozilla/5.0 (Linux; Android 10; SM-G975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.101 Mobile Safari/537.36")
b.device.name
=> "Unknown"

## What do you expect

b = Browser.new("Mozilla/5.0 (Linux; Android 10; SM-G975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.101 Mobile Safari/537.36")
b.device.name
=> "SM-G975F"

## What happened instead

See "How to reproduce"

## Software:

- Rails version: 5.2.4
- Browser gem version: 5.0.0

## Full backtrace

N/A

## Report

N/A

**Comment by fnando** [comment]
Would "Samsung Galaxy S10 (SM-G975F)" be better? I can retrieve an initial list of devices, and the community may keep it updated via pull requests. Does that make sense?

**Comment by koendehondt** [comment]
@fnando "Samsung Galaxy S10 (SM-G975F)"  is fine! Thank you.
