### ISSUE TITLE
Real version Internet Explorer in Compatibility View

### ISSUE THREAD

**Issue by kodram** [fnando/browser#51]
Browser: Internet Explorer 10

default:
**browser.version: 10**
request.env['HTTP_USER_AGENT']: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)

compatibility view:
**browser.version: 7**
request.env['HTTP_USER_AGENT']: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; Tablet PC 2.0; .NET4.0C; .NET4.0E)

I need a method to determine the real version browser. 
Maybe add some method for this?

I think for that you can check the layout engine (Trident version).

**Comment by stanhu** [comment]
:+1: 

A user requested this in GitLab: https://gitlab.com/gitlab-org/gitlab-ce/issues/2271 Any chance this can be added soon?

**Comment by fnando** [comment]
Hey! Dealing with this long standing issue. Can you all review PR #168 and maybe try it out? 

Since this breaks the current API detection, I'll do a major release.
