### ISSUE TITLE
Stripe listed as bot

### ISSUE THREAD

**Issue by Paradoxor** [fnando/browser#512]
Why is stripe defined as a bot?
We want to track our stribe webhooks with ahoy tracking since they are using your gem it took a while until I figured out that stripe is on the list. Is there a reason for this? And would it be possible to whitelist the webhooks from that?

Thanks in advance

**Comment by fnando** [comment]
I don't see a problem with that. In the meantime, you can tweak the list by adding the matching string to `Browser::Bot.bot_exceptions` or removing Stripe from `Browser::Bot.bots` with `Browser::Bot.bots.delete("stripe")`.

**Comment by Paradoxor** [comment]
Yes we have remove Stripe from the list. The question is why is a payment provider like stripe on that list but PayPal not?

Thanks for your answer.

**Comment by fnando** [comment]
Fixed by https://github.com/fnando/browser/pull/513
