### ISSUE TITLE
Ruby version requirement change in 6.0.0?

### ISSUE THREAD

**Issue by mjankowski** [fnando/browser#543]
Just saw the 6.0.0 release -- nice, thanks!

Curious about this ruby version req change - https://github.com/fnando/browser/commit/e54203b13995b4cc6199b521e430427a95ab4579#diff-53ec28e04e87eace119c08cf1afa508aa03532493a9e256ed8ddcd2fd0c72423R15 - I think ruby 3.0 was recently EOL'd but ruby 3.1 is still supported for another ~year or so ... https://www.ruby-lang.org/en/downloads/branches/

Was there a rubocop requirement or other ruby style thing somewhere in the recent changes that merited bumping all the way up to 3.2 minimum, or could 3.1 have been kept? Would like to bump the browser gem dep, but still have some legacy 3.1 installs to support.

(I originally left this as a comment on a commit, but realized that may not be super visible. Sorry about the effective double posting...)

**Comment by johan-smits** [comment]
I also ran into this issue. I'm using Debian stable and they are at Ruby `3.1`. Dropping the 3.1 seems a little to soon?

**Comment by westonganger** [comment]
To solve this I added the following monkey patch to my gem (or application

```ruby
config/initializers/browser_monkey_patches.rb

if Browser::VERSION.to_f < 6.0
  Browser::Base.class_eval do
    def chromium_based?
      false
    end
  end

  Browser::Chrome.class_eval do
    def chromium_based?
      true
    end
  end

  Browser::Edge.class_eval do
    def chromium_based?
      match? && ua.match?(/\bEdg\b/)
    end
  end
end
```

**Comment by mjankowski** [comment]
Closing this on assumption that there was a year mixup (3.1 is EOL in April 2025, but presumably maintainer read that as 2024?)

In ~4 months, this will be retroactively correct.
