### ISSUE TITLE
Gem can't tell if user is using ios, iphone or iPad when 'Request Desktop site' is turned on.

### ISSUE THREAD

**Issue by renatomolina** [fnando/browser#547]
## Description
`browser.platform.ios?` returns false when user is using the browser in a iOS but using 'Request Desktop site' option on Chrome.

## How to reproduce
1. Select `Request Desktop site` option on Chrome
2. Load the page

## What do you expect
Method should return true

## What happened instead
Method returns false

## Software:
- Rails version: 7.0.8.1
- Browser gem version: 5.3.1

## Full backtrace
```text
n/a
```

## Report
n/a

**Comment by fnando** [comment]
@renatomolina Can you please paste the user agents that are being used and what's the expected result for each of them? I think this cannot be solved, because the user agent is likely hiding stuff that can be recognized as something different.

**Comment by renatomolina** [comment]
@fnando should be doable, for some reason another gem can identify it correctly.

**Comment by fnando** [comment]
@renatomolina can you please link me to it? I can take a look, but I doubt that's the case.

**Comment by renatomolina** [comment]
@fnando [this gem](https://github.com/podigee/device_detector) does return `Chrome Mobile iOS` when I call `.name`. I'm still reading their code and trying to figure out how they did.

**Comment by fnando** [comment]
My guess is that `CriOS/130` is something made up, so it's likely just assuming it comes from iOS, which may be the case most of the time?

Maybe we can do the same.

https://github.com/podigee/device_detector/blob/e68ee76b1cc55360074b9e3687ab4e49f8956315/regexes/client/browsers.yml#L2688C11-L2692

**Comment by fnando** [comment]
@renatomolina btw, what's the browser being used here? Safari? The latest iOS returns this instead: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15`, cannot be bypassed (device_detector says it's a desktop).

**Comment by renatomolina** [comment]
@fnando I got that agent from using Chrome on latest iOS.

**Comment by renatomolina** [comment]
@fnando saw the PR. thanks for working on this so fast. this is awesome
