### ISSUE TITLE
Support "gnome web" / epiphany browser?

### ISSUE THREAD

**Issue by mjankowski** [fnando/browser#551]
Background: https://github.com/mastodon/mastodon/issues/32274

Happy to add this one in, but readme says to ask first before building. Thoughts?

**Comment by fnando** [comment]
Oh yeah, this should be fine. If you have the user agents, I can also add it, whatever you prefer.

**Comment by mjankowski** [comment]
Cool. Other than a list like this - https://whatmyuseragent.com/browser/ep/gnome-web/3 - I'm not 100% sure (have not heard back on that issue yet, and I don't personally use the browser).
