### ISSUE TITLE
Modern browsers

### ISSUE THREAD

**Issue by suciuvlad** [fnando/browser#62]
Internet Explorer 9 doesn't support xhr2(http://caniuse.com/xhr2). Should it be considered a modern browser?

Further reading: http://people.mozilla.org/~prouget/ie9/

**Comment by louis** [comment]
Hi, where does this code go?  Not having success when I put in application.rb.

**Comment by jalcine** [comment]
If you can't beat them (all) :wink:, good move @fnando !
