### ISSUE TITLE
Detect in app browsers [Feature request]

### ISSUE THREAD

**Issue by Bertg** [fnando/browser#94]
[This article](http://welcome.totheinter.net/2011/01/12/stealing-passwords-is-easy-in-native-mobile-apps-despite-oauth/) warns us of the dangers of in app browsers.

Certain platforms (IOS) contain information about the app the is being used. It would be great if we could ask if the browser is "embedded" and maybe even which app it is.

What do you think?

**Comment by fnando** [comment]
You can now use `browser.platform.ios_webview?` and `browser.platform.ios_app?` on v2.0.0, just released.
